import { TeamplteTableProvider } from "@/components/menu-table-editor/table-provider";
import { TemplateMenuTable } from "@/components/menu-table-editor/template-menu-table";

export default async function MenuTemplatePage() {
  const templateCategories = [
    {
      id: "1",
      category_name: "type",
      display_name: "種類",
      width: 100,
      order: 1,
    },
    {
      id: "2",
      category_name: "distance",
      display_name: "距離",
      width: 50,
      order: 2,
    },
    {
      id: "3",
      category_name: "number_of_sets",
      display_name: "本数",
      width: 50,
      order: 3,
    },
    {
      id: "4",
      category_name: "sets",
      display_name: "セット数",
      width: 80,
      order: 4,
    },
    {
      id: "5",
      category_name: "style",
      display_name: "種目",
      width: 120,
      order: 5,
    },
    {
      id: "6",
      category_name: "cycle",
      display_name: "サイクル",
      width: 80,
      order: 6,
    },
    {
      id: "7",
      category_name: "content",
      display_name: "内容",
      width: 600,
      order: 7,
    },
    {
      id: "8",
      category_name: "strength",
      display_name: "強度",
      width: 60,
      order: 8,
    },
    {
      id: "9",
      category_name: "total_distance",
      display_name: "総距離",
      width: 100,
      order: 9,
    },
    {
      id: "10",
      category_name: "total_time",
      display_name: "総時間",
      width: 100,
      order: 10,
    },
  ];

  const templateItems = [
    {
      id: "1",
      type: "Swim",
      distance: "200",
      number_of_sets: 1,
      sets: 1,
      style: "CHO",
      cycle: "4'00",
      content: "",
      strength: "A1",
      total_distance: "200",
      total_time: "4'00",
    },
    {
      id: "2",
      type: "Swim",
      distance: "100",
      number_of_sets: 2,
      sets: 3,
      style: "IM",
      cycle: "1'40",
      content: "set des",
      strength: "EN1",
      total_distance: "600",
      total_time: "10'00",
    },
    {
      id: "3",
      type: "Pull",
      distance: "50",
      number_of_sets: 11,
      sets: 1,
      style: "",
      cycle: "0'50",
      content: "4Fr+IMO+IMO/Fr",
      strength: "EN1",
      total_distance: "550",
      total_time: "9'10",
    },
    {
      id: "4",
      type: "Pull",
      distance: "100",
      number_of_sets: 3,
      sets: 1,
      style: "S1",
      cycle: "1'50",
      content: "Des",
      strength: "EN3",
      total_distance: "300",
      total_time: "5'30",
    },
    {
      id: "5",
      type: "Swim",
      distance: "100",
      number_of_sets: 1,
      sets: 1,
      style: "CHO",
      cycle: "3'00",
      content: "Loosen",
      strength: "A1",
      total_distance: "100",
      total_time: "3'00",
    },
    {
      id: "6",
      type: "Drill",
      distance: "50",
      number_of_sets: 5,
      sets: 1,
      style: "CHO",
      cycle: "1'10",
      content: "",
      strength: "A2",
      total_distance: "250",
      total_time: "5'50",
    },
    {
      id: "7",
      type: "Drill",
      distance: "50",
      number_of_sets: 4,
      sets: 1,
      style: "S1",
      cycle: "1'10",
      content: "set up",
      strength: "",
      total_distance: "200",
      total_time: "4'40",
    },
    {
      id: "8",
      type: "Broken",
      distance: "50",
      number_of_sets: 1,
      sets: 1,
      style: "",
      cycle: "0'50",
      content: "",
      strength: "AN1",
      total_distance: "50",
      total_time: "0'50",
    },
    {
      id: "9",
      type: "Broken",
      distance: "100",
      number_of_sets: 1,
      sets: 1,
      style: "",
      cycle: "1'30",
      content: "Max!",
      strength: "AN1",
      total_distance: "100",
      total_time: "1'30",
    },
    {
      id: "10",
      type: "Broken",
      distance: "50",
      number_of_sets: 1,
      sets: 1,
      style: "",
      cycle: "0'40",
      content: "",
      strength: "AN1",
      total_distance: "50",
      total_time: "0'40",
    },
    {
      id: "11",
      type: "Broken",
      distance: "0",
      number_of_sets: 1,
      sets: 1,
      style: "",
      cycle: "7'00",
      content: "rest",
      strength: "",
      total_distance: "0",
      total_time: "7'00",
    },
    {
      id: "12",
      type: "Broken",
      distance: "50",
      number_of_sets: 2,
      sets: 1,
      style: "",
      cycle: "0'40",
      content: "Max!",
      strength: "AN1",
      total_distance: "100",
      total_time: "1'20",
    },
    {
      id: "13",
      type: "Broken",
      distance: "0",
      number_of_sets: 1,
      sets: 1,
      style: "",
      cycle: "6'40",
      content: "rest",
      strength: "",
      total_distance: "0",
      total_time: "6'40",
    },
    {
      id: "14",
      type: "Down",
      distance: "400",
      number_of_sets: 1,
      sets: 1,
      style: "",
      cycle: "8'00",
      content: "",
      strength: "",
      total_distance: "400",
      total_time: "8'00",
    },
  ];

  return (
    <TeamplteTableProvider
      templateCategories={templateCategories}
      templateItems={templateItems}
    >
      <TemplateMenuTable />
    </TeamplteTableProvider>
  );
}
